# Generated by Django 3.0.5 on 2023-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default_Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_file', models.FileField(default='default.docx', upload_to='template_files')),
                ('template_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
